apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-backend
spec:
  type: ClusterIP
  selector:
    app: {{ include "myapp.name" . }}-backend
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}