apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "myapp.name" . }}-frontend
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}