frontend:
  image:
    repository: jubbuseacrinmh.azurecr.io/aks-demo-app-dev-frontend
    tag: "123"  # Use GitHub Actions to dynamically replace this
  containerPort: 3000
  servicePort: 80

backend:
  image:
    repository: jubbuseacrinmh.azurecr.io/aks-demo-app-dev-backend
    tag: "123"
  containerPort: 5000
  servicePort: 80
