frontend:
  image:
    repository: jubbuseacrinmh.azurecr.io/aks-demo-app-dev-frontend
    tag: latest
  containerPort: 3000
  servicePort: 80

backend:
  image:
    repository: jubbuseacrinmh.azurecr.io/aks-demo-app-dev-backend
    tag: latest
  containerPort: 5000
  servicePort: 80