frontend:
  image: $ACR_NAME/frontend:${{ github.run_number }}
  port: 80

backend:
  image: $ACR_NAME/backend:${{ github.run_number }}
  port: 5000

env:
  normal:
    APP_ENV: "development"
    LOG_LEVEL: "debug"
  secret:
    DB_USERNAME: "demo"
    DB_PASSWORD: "demo"
    API_KEY: "demo"
secret:
  name: app-env-secret
