name: Build and Deploy Frontend and Backend to AKS via Helm

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

env:
  ACR_NAME: jubbuseacrinmh.azurecr.io
  RESOURCE_GROUP: verito-aks-rg
  CLUSTER_NAME: verito-aks-cluster
  NAMESPACE: default

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event.inputs.environment }}
      IMAGE_NAME: aks-demo-app-${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: ACR Login
        run: az acr login --name jubbuseacrinmh

      - name: Build and push frontend image
        run: |
          docker build -t $ACR_NAME/${{ env.IMAGE_NAME }}-frontend:${{ github.run_number }} ./frontend
          docker push $ACR_NAME/${{ env.IMAGE_NAME }}-frontend:${{ github.run_number }}

      - name: Build and push backend image
        run: |
          docker build -t $ACR_NAME/${{ env.IMAGE_NAME }}-backend:${{ github.run_number }} ./backend
          docker push $ACR_NAME/${{ env.IMAGE_NAME }}-backend:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    env:
      ENV: ${{ github.event.inputs.environment }}
      IMAGE_NAME: aks-demo-app-${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Generate values file for Helm
        run: |
          cat <<EOF > myapp/values-${{ env.ENV }}.yaml
          frontend:
            image: $ACR_NAME/${{ env.IMAGE_NAME }}-frontend:${{ github.run_number }}
            port: 80
          backend:
            image: $ACR_NAME/${{ env.IMAGE_NAME }}-backend:${{ github.run_number }}
            port: 5000
          EOF
      - name: Deploy with Helm
        run: |
          helm upgrade --install fullstack-app ./myapp -f myapp/values-${{ env.ENV }}.yaml --namespace ${{ env.NAMESPACE }} --create-namespace
